name: Deploy to GoDaddy (FTPS) - Final

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      SITE_HOST: www.allegiancelistmarketing.com

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Tools
        run: sudo apt-get update && sudo apt-get install -y lftp curl jq

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Validate Data Contracts
        run: |
          set -euxo pipefail
          npx -y ajv-cli@5 validate -s assets/data/datacards.schema.json -d assets/data/datacards.json
          jq -e "type==\"array\"" assets/data/datacards.json >/dev/null

      - name: Prepare Artifact with Cache-Proof Marker
        run: |
          set -euxo pipefail
          rm -rf out
          rsync -av --delete \
            --exclude ".git" --exclude ".github" --exclude "out" \
            --exclude "*.bak.*" --exclude ".DS_Store" \
            ./ out/
          echo "Verified: ${GITHUB_SHA}" > "out/deploy-${GITHUB_SHA}.txt"
          echo "--> Created unique verification file: out/deploy-${GITHUB_SHA}.txt"

      - name: Upload via FTPS
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_DIR: ${{ secrets.FTP_DIR }}
        run: |
          set -euxo pipefail
          : "${FTP_DIR:=.}"
          lftp -c "
            set ftp:passive-mode true;
            set ftp:ssl-force true;
            set ftp:ssl-protect-data true;
            set ssl:verify-certificate false;
            set net:max-retries 3;
            set net:timeout 45;
            open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER;
            lcd out;
            mirror --reverse --delete --verbose=3 . .;
          "

