name: Deploy to GoDaddy (FTPS, robust)
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare artifact
        run: |
          rm -rf out
          mkdir out
          rsync -av --delete \
            --exclude ".git" \
            --exclude ".github" \
            --exclude "out" \
            --exclude "*.bak.*" \
            --exclude ".DS_Store" \
            ./ ./out/

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Verify remote path (pwd/ls)
        env:
          FTP_SERVER:   ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_DIR:      ${{ secrets.FTP_DIR }}
        run: |
          # default to public_html if FTP_DIR is empty
          FTP_DIR="${FTP_DIR:-public_html}"
          echo "Using FTP_DIR='$FTP_DIR'"
          lftp -u "$FTP_USERNAME","$FTP_PASSWORD" "$FTP_SERVER" <<LFTP_CMDS
          set ftp:passive-mode true
          set ftp:ssl-force true
          set ftp:ssl-protect-data true
          set ssl:verify-certificate false
          echo ">>> pwd BEFORE"
          pwd
          echo ">>> ls BEFORE"
          ls -la
          echo ">>> cd $FTP_DIR"
          cd $FTP_DIR
          echo ">>> pwd AFTER"
          pwd
          echo ">>> ls AFTER"
          ls -la
          bye
LFTP_CMDS

      - name: Upload via FTPS (explicit TLS) with retries
        env:
          FTP_SERVER:   ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_DIR:      ${{ secrets.FTP_DIR }}
        run: |
          FTP_DIR="${FTP_DIR:-public_html}"
          echo "Mirroring to FTP_DIR='$FTP_DIR'"
          lftp -u "$FTP_USERNAME","$FTP_PASSWORD" "$FTP_SERVER" <<'LFTP_CMDS'
          set net:max-retries 5
          set net:persist-retries 3
          set net:timeout 30
          set net:reconnect-interval-base 5
          set net:reconnect-interval-max 60
          set ftp:passive-mode true
          set ftp:ssl-force true
          set ftp:ssl-protect-data true
          set xfer:clobber on
          set ssl:verify-certificate false
          mkdir -p $FTP_DIR
          mirror -R --verbose=3 --parallel=1 \
            --exclude-glob ".git*" \
            --exclude-glob ".github/*" \
            --exclude-glob "out/*" \
            --exclude-glob "*.bak.*" \
            --exclude-glob ".DS_Store" \
            out/ $FTP_DIR/
          bye
LFTP_CMDS
