name: Deploy to GoDaddy (FTPS, robust)
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare artifact
        run: |
          rm -rf out
          mkdir out
          rsync -av --delete \
            --exclude ".git" \
            --exclude ".github" \
            --exclude "out" \
            --exclude "*.bak.*" \
            --exclude ".DS_Store" \
            ./ ./out/

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Verify remote path (pwd/ls)
        env:
          FTP_SERVER:   ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_DIR:      ${{ secrets.FTP_DIR }}
        run: |
          set -e
          FTP_DIR="${FTP_DIR:-public_html}"
          echo "Using FTP_DIR='$FTP_DIR'"
          lftp -u "$FTP_USERNAME","$FTP_PASSWORD" "$FTP_SERVER" -e "set ftp:passive-mode true; set ftp:ssl-force true; set ftp:ssl-protect-data true; set ssl:verify-certificate false; pwd; ls -la; cd $FTP_DIR; pwd; ls -la; bye"

      - name: Upload via FTPS (explicit TLS) with retries
        env:
          FTP_SERVER:   ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_DIR:      ${{ secrets.FTP_DIR }}
        run: |
          set -e
          FTP_DIR="${FTP_DIR:-public_html}"
          echo "Mirroring to FTP_DIR='$FTP_DIR'"
          lftp -u "$FTP_USERNAME","$FTP_PASSWORD" "$FTP_SERVER" -e "set net:max-retries 5; set net:persist-retries 3; set net:timeout 30; set net:reconnect-interval-base 5; set net:reconnect-interval-max 60; set ftp:passive-mode true; set ftp:ssl-force true; set ftp:ssl-protect-data true; set xfer:clobber on; set ssl:verify-certificate false; mkdir -p $FTP_DIR; mirror -R --ignore-time --delete --verbose=3 --parallel=1 --exclude-glob .DS_Store out/ $FTP_DIR/; bye"
